name: ripple_healthcare
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  pinput: ^3.0.1
  http: ^1.1.2
  get_storage: ^2.1.1
  fluttertoast: ^8.2.4
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  fl_chart: ^0.66.1
  syncfusion_flutter_charts: ^24.2.4+3
  simple_progress_indicators: ^0.2.0
  smooth_page_indicator: ^1.1.0
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets\fonts\Urbanist-Bold.ttf
        - asset: assets\fonts\Urbanist-Regular.ttf
