part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOG_IN = _Paths.LOG_IN;
  static const SPLASHSCRCEEN = _Paths.SPLASHSCRCEEN;
  static const OTP_VERIFY = _Paths.OTP_VERIFY;
  static const REGISTER = _Paths.REGISTER;
  static const TRAINING_EXP = _Paths.TRAINING_EXP;
  static const SUCCESS_VIEW = _Paths.SUCCESS_VIEW;
  static const DASHBOARD_VIEW = _Paths.DASHBOARD_VIEW;
  static const ONBOARD = _Paths.ONBOARD;
  static const SUCCESSLOGIN = _Paths.SUCCESSLOGIN;
  static const HELLO_SCREEN = _Paths.HELLO_SCREEN;
  static const QUE_SCREEN = _Paths.QUE_SCREEN;
  static const HIP_PRO_BLUETOOTH_FLOW = _Paths.HIP_PRO_BLUETOOTH_FLOW;
  static const BLUETOOTH_CONNECT_PROCESS = _Paths.BLUETOOTH_CONNECT_PROCESS;
  static const TEST_STAGE_WISE = _Paths.TEST_STAGE_WISE;
  static const STAGE_VIEW = _Paths.STAGE_VIEW;
  static const TEST_DONE = _Paths.TEST_DONE;
  static const CONTROLL = _Paths.CONTROLL;
  static const BOTTOM_NAV_BAR = _Paths.BOTTOM_NAV_BAR;
  static const MEDICATION = _Paths.MEDICATION;
  static const WALKING_STEPS_CHART = _Paths.WALKING_STEPS_CHART;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const PROFILE = _Paths.PROFILE;
  static const STEADY_STEPS_ONBOARDING = _Paths.STEADY_STEPS_ONBOARDING;
  static const STEADY_STEPS_PAGEVIEW = _Paths.STEADY_STEPS_PAGEVIEW;
  static const STEADY_STEPS_DASHBOARD = _Paths.STEADY_STEPS_DASHBOARD;
  static const BALANCE_TESTING = _Paths.BALANCE_TESTING;
  static const MCQ_TEST_VIEW = _Paths.MCQ_TEST_VIEW;
  static const WELL_DONE_SCREEN = _Paths.WELL_DONE_SCREEN;
  static const STEADY_STEP_PROGRESS = _Paths.STEADY_STEP_PROGRESS;
  static const REWARD = _Paths.REWARD;
  static const DAILY_CHALLENGES = _Paths.DAILY_CHALLENGES;
  static const DAILY_CHALLENGES_TEST_VIEW = _Paths.DAILY_CHALLENGES_TEST_VIEW;
  static const DAILY_CHALLENGES_MCQ_VIEW = _Paths.DAILY_CHALLENGES_MCQ_VIEW;
  static const STEADY_STEP_BALANCE_TEST = _Paths.STEADY_STEP_BALANCE_TEST;
  static const STEADY_STEP_STAGE_VIEW = _Paths.STEADY_STEP_STAGE_VIEW;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOG_IN = '/log-in';
  static const SPLASHSCRCEEN = '/SPLASHSCRCEEN';
  static const ONBOARD = '/onboard';
  static const OTP_VERIFY = '/otp-verify';
  static const REGISTER = '/register';
  static const TRAINING_EXP = '/trainig-exp';
  static const SUCCESS_VIEW = '/success-view';
  static const DASHBOARD_VIEW = '/dashboard-view';
  static const SUCCESSLOGIN = '/success-login-view';
  static const HELLO_SCREEN = '/hello-screen';
  static const QUE_SCREEN = '/que-screen';
  static const HIP_PRO_BLUETOOTH_FLOW = '/hip-pro-bluetooth-flow';
  static const BLUETOOTH_CONNECT_PROCESS = '/bluetooth-connect-process';
  static const TEST_STAGE_WISE = '/test-stage-wise';
  static const STAGE_VIEW = '/stage-view';
  static const TEST_DONE = '/test-done';
  static const CONTROLL = '/controll';
  static const BOTTOM_NAV_BAR = '/bottom-nav-bar';
  static const MEDICATION = '/medication';
  static const WALKING_STEPS_CHART = '/walking-steps-chart';
  static const NOTIFICATIONS = '/notifications';
  static const PROFILE = '/profile';
  static const STEADY_STEPS_ONBOARDING = '/steady-steps-onboarding';
  static const STEADY_STEPS_PAGEVIEW = '/steady-steps-pageview';
  static const STEADY_STEPS_DASHBOARD = '/steady-steps-dashboard';
  static const BALANCE_TESTING = '/balance-testing';
  static const MCQ_TEST_VIEW = '/mcq-test-view';
  static const WELL_DONE_SCREEN = '/well-done-screen';
  static const STEADY_STEP_PROGRESS = '/steady-step-progress';
  static const REWARD = '/reward';
  static const DAILY_CHALLENGES = '/daily-challenges';
  static const DAILY_CHALLENGES_TEST_VIEW = '/daily-challenges-test-view';
  static const DAILY_CHALLENGES_MCQ_VIEW = '/daily-challenges-mcq-view';
  static const STEADY_STEP_BALANCE_TEST = '/steady-step-balance-test';
  static const STEADY_STEP_STAGE_VIEW = '/steady-step-stage-view';
}
